#!/usr/bin/env bash
# scrip that transfers a file from a client to a server using scp

#check if the number of arguments passed is less than 4
if [ $# -lt 4 ]; then
	printf "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "${4}" "${1}" "${3}@${2}:~/"

exit 0
