#!/usr/bin/env bash
#script to install nginx on a server

#update the apt package and install nginx
apt-get update
apt-get -y install nginx

#adjust firewall to allow access to nginx
#configure to access HTTP profile and listen only on port 80
ufw allow 'Nginx HTTP'

#return a custom message when querying Nginx at root with curl
echo "Hello World!" > /var/www/html/index-nginx-debian.html

#restart nginx
service nginx start

