#!/usr/bin/env bash
#script to install nginx on a server

#update the apt package and install nginx
apt-get update
apt-get -y install nginx

#adjust firewall to allow access to nginx
#configure to access HTTP profile and listen only on port 80
ufw allow 'Nginx HTTP'

#return a custom message when querying Nginx at root with curl
cat << EOF > /var/www/html/index.html
Hello World!
EOF

# Define the redirect URL
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

#configure nginx to redirect to another page in a new server block
cat << EOF > /etc/nginx/sites-available/redirect.conf
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

	location = /redirect_me {
		return 301 $REDIRECT_URL;
	}
}
EOF

#create a symbolic link to enable the new configuration file
ln -s /etc/ngix/sites-available/redirect.conf /etc/nginx/sites-enabled/

#test the nginx configuration and  restart nginx
nginx -t && service nginx restart
