#!/usr/bin/env bash
#script to install nginx on a server

#update the apt package and install nginx
apt-get update
apt-get -y install nginx

#adjust firewall to allow access to nginx
#configure to access HTTP profile and listen only on port 80
ufw allow 'Nginx HTTP'

#return a custom message when querying Nginx at root with curl
cat << EOF > /var/www/html/index.html
Hello World!
EOF

# configure nginx to redirect to another page
sed -i '/listen 80 default_server;/a \\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
#sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# restart nginx
service nginx start
