#!/usr/bin/env bash
#script to install nginx on a server

#update the apt package and install nginx
apt-get update
apt-get -y install nginx

#adjust firewall to allow access to nginx
#configure to access HTTP profile and listen only on port 80
ufw allow 'Nginx HTTP'

#create a custom 404 page to return custom message
cat << EOF > /var/www/html/404.html
Ceci n'est pas une page
EOF

# configure nginx to redirect to another page
sed -i '/listen 80 default_server;/a error_page 404 /404.html; \nlocation /404.html {\ninternal;\n}' /etc/nginx/sites-available/default

# restart nginx
service nginx restart
