#!/usr/bin/env bash
#Bash script to print Best School 10 times
count=1

while [ $count -le 10 ]
do
  if [ $count -eq 9 ]
  then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi

  count=$((count + 1))
done
