#!/usr/bin/env bash
#Basg script to display unique string in 4th, 8th iterations
count=1

while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad Luck"
  elif [ $count -eq 8 ]
  then
    echo "good Luck"
  else
    echo "Best School"
  fi

  count=$((count + 1))
done
