#!/usr/bin/env bash
# script to configure container to run nginx as nginx user

# check if nginx user exists
if id -u nginx >/dev/null 2>&1; then
    echo "nginx user already exists"
else
    # create a user "nginx"
    password=$(openssl rand -base64 12)
    sudo adduser --disabled-password --gecos "" nginx
    echo "nginx:$password" | sudo chpasswd
fi

# configure nginx to run as nginx user
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

# configure nginx to listen on all active IPs on port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf
pkill apache2

# start nginx
sudo -u nginx  service nginx start
