#!/usr/bin/env bash
# script to configure container to run nginx as nginx user

# check if nginx user exists
if id -u nginx >/dev/null 2>&1; then
    echo "nginx user already exists"
else
    # create a user "nginx"
    password=$(openssl rand -base64 12)
    sudo adduser --disabled-password --gecos "" nginx
    echo "nginx:$password" | sudo chpasswd
fi

# configure nginx to run as nginx user
sudo sed -i 's/^user www-data;/user nginx;/' /etc/nginx/nginx.conf

# configure nginx to listen on all active IPs on port 8080
sudo sed -i 's/^# server {/server {\n    listen 8080 default_server;/g' /etc/nginx/sites-available/default

# start nginx
sudo service nginx start
